export const mockTelegramData = {
  query_id: '1234567890abcdef',
  user: {
    id: 252571304,
    first_name: 'John',
    last_name: 'Doe',
    username: '@kostya',
    language_code: 'en',
  },
  receiver: {
    id: 202020,
    first_name: 'Jane',
    last_name: 'Smith',
    username: '@badavoo',
    language_code: 'en',
  },
  chat: {
    id: 208165379,
    title: 'Sample Group',
    type: 'supergroup',
    members_count: 100,
  },
  chat_type: 'group',
  chat_instance: 'abcdef1234567890',
  start_param: 'sample_start_param',
  can_send_after: 30,
  auth_date: 1673616000, // This is just a sample UNIX timestamp.
  hash: 'f0e2b49f9f1d104ada8f5f960ecdf29b', // A fictitious hash value.
}

export const skillsDict = [
  { id: 'analytics', name: '📊 Аналитика' },
  { id: 'blockchain', name: '🔗 Блокчейн' },
  { id: 'bizdev', name: '😎 Бизнес развитие' },
  { id: 'dataScience', name: '👩‍🔬Data Science' },
  { id: 'ecommerce', name: '🛍️ E-commerce' },
  { id: 'consulting', name: '🧠 Консалтинг' },
  { id: 'logistics', name: '🚚 Логистика' },
  { id: 'leadership', name: '🦸‍♀️ Лидерство' },
  { id: 'mobileDev', name: '📲 Мобильная разработка' },
  { id: 'eventManagement', name: '📆 Организация мероприятий' },
  { id: 'operationsManagement', name: '🔨 Операционный менеджмент' },
  { id: 'programming', name: '💻 Программирование' },
  { id: 'advertisement', name: '📈Реклама и маркетинг' },
  { id: 'startups', name: '🚀 Стартапы' },
  { id: 'finance', name: '💰 Финансы' },
  { id: 'productManagement', name: '🎯 Управление продуктом' },
  { id: 'hr', name: '👥 HR' },
  { id: 'investment', name: '💵 Инвестиции' },
  { id: 'uxUiDesign', name: '🎨 UX/UI дизайн' },
  { id: 'law', name: '⚖️ Юриспруденция' },
  // {id: 'sales', name: '💼 Продажи'},
  // {id: 'marketing', name: '📈 Маркетинг'},
  // {id: 'projectManagement', name: '📝 Проект-менеджмент'},
  // {id: 'innovations', name: '💡 Инновации'},
  // {id: 'seo', name: '🔎 SEO/SEM'},
  // {id: 'copyrighting', name: '🖊️ Копирайтинг'},
  // {id: 'smm', name: '📱 SMM'},
  // {id: 'pr', name: '📢 PR'},
]

export const hobbiesDict = [
  { id: 'activeTime', name: '🏃‍♀️ Активный отдых и спорт' },
  { id: 'cars', name: '🚗 Автомобили и мотоциклы' },
  { id: 'vine', name: '🍷 Вина и гастрономия' },
  { id: 'volunteering', name: '🤝 Волонтерство' },
  { id: 'language', name: '🗣️ Изучение языков' },
  { id: 'culture', name: '🎨 Искусство и культура' },
  { id: 'pets', name: '😼 Животные' },
  { id: 'mindfulness', name: '‍🧘️ Йога и медитация' },
  { id: 'health', name: '🍎 Здоровый образ жизни' },
  { id: 'cooking', name: '🍳 Кулинария' },
  { id: 'literature', name: '📚 Литература' },
  { id: 'fashion', name: '👗 Мода и стиль' },
  { id: 'music', name: '🎵 Музыка' },
  { id: 'science', name: '🔬 Наука и технологии' },
  { id: 'adventure', name: '️🏕 Походы и природа' },
  { id: 'travel', name: '🌍 Путешествия и экспедиции' },
  { id: 'gardening', name: '🌱 Садоводство' },
  { id: 'photography', name: '📸 Фото и видео' },
  { id: 'handmade', name: '👐 Хендмейд' },
  { id: 'ecology', name: '🌳 Экология' },
  // {id: 'dance', name: '💃 Танцы'},
  // {id: 'cinema', name: '🎬 Кино и театр'},
  // {id: 'socialNetwork', name: '📱 Социальные сети'},
  // {id: 'gaming', name: '🕹Видеоигры'},
  // {id: 'boardGames', name: '🎲 Настольные игры'},
  // {id: 'hiking', name: '⛰Хайкинг'},
  // {id: 'running', name: '👟 Бег'},
  // {id: 'tennis', name: '🎾 Теннис/Падел/Сквош'},
  // {id: 'badminton', name: '🏸 Бадминтон'},
  // {id: 'surfing', name: '🏄‍♀️ Серфинг'},
  // {id: 'skate', name: '🛹️ Скейтборд'},
  // {id: 'snowboard', name: '🏂️ Сноуборд'},
]
